#version 430
layout(local_size_x = 32) in;

layout(std140,binding = 0) uniform params {
    float t0;  // 0
    float beta; // 4
    int K; // 8
    int stiffness; // 12
    int edge_size; // 16
    float alpha; // 20
    float m_h; // 24
    int gradient_size; // 28
    int vertex_size; // 32
    int attachment_size; // 36
    int _pad0; // 40
    int _pad1; // 44
};

uniform float currentEnergy;
uniform float grad_dot_d;


layout(std430, binding = 3) buffer Data {
    float energy[];
};

layout(std430,binding = 5) buffer Flags {
    int valid[];
};

void main() {
    uint i = gl_GlobalInvocationID.x;

    if (i >= uint(K)) {
        return;
    }

    float t = t0 * pow(beta, float(i));
    float rhs = currentEnergy + alpha * t * grad_dot_d;

    valid[i] = (energy[i] <= rhs) ? 1 : 0;
}
