#version 430

layout(local_size_x = 256) in;

layout(std140, binding = 0) uniform params {
    float t0;
    float beta;
    int K;
    int stiffness;
    int edge_size;
    float alpha;
    float m_h;
    int gradient_size;
    int vertex_size;
    int attachment_size;
    int _pad0;
    int _pad1;
};

layout(std430, binding = 2) buffer XBuffer {
    float x_pos[];
};

layout(std430, binding = 7) readonly buffer DescentBuffer {
    float d[];
};

layout(std430, binding = 6) readonly buffer LineSearchResult {
    int chosen_i;
    int accepted;
    float step;
    float accepted_energy;
};

uniform uint size;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < size) {
        x_pos[idx] += d[idx] * step;
    }
}
