#version 430

layout( local_size_x = 1 ) in;

//uniform vec3 m_external_force;
//uniform float stiffness;
//uniform float h_square;
//uniform float m_rest_length;
//uniform float m_mass_matrix; //  m_mesh->m_mass_matrix
uniform float m_h;
uniform uint gradient_size;

layout(std430, binding = 1) buffer gradientBuffer {
    float gradient[];
};

layout(std430, binding = 2) buffer x_posBuffer {
    float x_pos[];
};

layout(std430, binding = 8) buffer m_y {
    float m_y[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;

    if(idx < gradient_size){
        gradient[idx] = m_mass_matrix * (x[idx] - m_y[idx]) + h_square * gradient[idx];
    }

}
