#version 430

layout( local_size_x = 1 ) in;

layout(std140,binding = 0) uniform params {
    float t0;  // 0
    float beta; // 4
    int K; // 8
    int stifness; // 12
    int edge_size; // 16
    float alpha; // 20
    float m_h; // 24
    int gradient_size; // 28
};


layout(std430, binding = 1) buffer gradientBuffer {
    float gradient[];
};

layout(std430, binding = 2) buffer x_posBuffer {
    float x_pos[];
};

layout(std430, binding = 8) buffer m_y {
    float m_y[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;

    if(idx < gradient_size){
        gradient[idx] = m_mass_matrix * (x[idx] - m_y[idx]) + m_h * m_h * gradient[idx];
    }

}
