#version 430

layout( local_size_x = 256 ) in;

uniform float rest_length;

layout(std140,binding = 9) uniform params {
    float t0;  // 0
    float beta; // 4
    int K; // 8
    int stiffness; // 12
    int edge_size; // 16
    float alpha; // 20
    float m_h; // 24
    int gradient_size; // 28
};

struct Edge
{
    uint m_v1, m_v2;
    uint m_tri1, m_tri2;
};

layout(std430, binding = 0) buffer EdgeBuffer {
    Edge edges[];
};

layout(std430, binding = 1) buffer gradientBuffer {
    float gradient[];
};

layout(std430, binding = 2) buffer x_posBuffer {
    float x_pos[];
};

layout(std430, binding = 3) buffer Data {
    float energy;
};
layout(std430, binding = 8) buffer m_y {
    float m_y[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;

    if(idx < edge_size){
        Edge e = edges[idx];

        // 获取顶点索引
        uint i = e.m_v1 * 3;
        uint j = e.m_v2 * 3;

        vec3 p_i = vec3(x_pos[i], x_pos[i+1], x_pos[i+2]);
        vec3 p_j = vec3(x_pos[j], x_pos[j+1], x_pos[j+2]);

        vec3 x_ij = p_i - p_j;

        float dist = length(x_ij);
        float ld_ij = dist - rest_length;

        float e_ij = 0.5 * float(stiffness) * ld_ij * ld_ij;

        atomicAdd(energy, e_ij);
    }

}
